### ISSUE TITLE
Migrate to latest express version

### ISSUE THREAD

**Issue by dpecos** [dpecos/keyring#24]

**Comment by dpecos** [comment]
Also check these errors:

keyring-0 (err): Wed, 14 Jan 2015 15:06:11 GMT express deprecated app.del: Use app.delete instead at routes/mysql/category.js:42:8
keyring-0 (err): Wed, 14 Jan 2015 15:06:11 GMT express deprecated app.del: Use app.delete instead at routes/mysql/entry.js:84:8

**Comment by dpecos** [comment]
npm-check-updates can be useful to check all packages updates
